In [95]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import seaborn as sns

###**Object creation**

Series를 만드는 방법

In [96]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DataFrame을 만드는 방법

In [97]:
#random값으로 넣는방법
dates = pd.date_range("20130101", periods = 6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [98]:
df = pd.DataFrame(np.random.randn(6, 4), index = dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.293807  0.987193 -0.809326 -0.111135
2013-01-02 -0.734789  0.080896 -0.560598  1.824775
2013-01-03  0.214790  1.465058  0.656087 -1.144362
2013-01-04 -0.140319  0.042732  0.442117 -0.511530
2013-01-05 -1.909196 -1.047267 -0.264858 -0.839969
2013-01-06 -0.711966 -1.916296 -3.634960  0.367112

In [99]:
#Dictionary로 넣는방법
df2 = pd.DataFrame({
    "A" : 1.0,
    "B" : pd.Timestamp("20130102"),
    "C" : pd.Series(1, index=list(range(4)), dtype="float32"),
    "D" : pd.array([3] * 4, dtype="int32"),
    "E" : pd.Categorical(["test", "train", "test", "train"]),
    "F" : "foo"
})

df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [100]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      float32
 3   D       4 non-null      int32
 4   E       4 non-null      category
 5   F       4 non-null      object
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 260.0+ bytes

In [101]:
#각 컬럼들은 다른 타입을 가지고 있다.
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [102]:
#df2. ABCDE 모두 .찍은 뒤에 항목들중에 나온다.

###**.Viewing data**

In [103]:
df.head() ##데이터 프레임의 위 n개항목 표시

                   A         B         C         D
2013-01-01  0.293807  0.987193 -0.809326 -0.111135
2013-01-02 -0.734789  0.080896 -0.560598  1.824775
2013-01-03  0.214790  1.465058  0.656087 -1.144362
2013-01-04 -0.140319  0.042732  0.442117 -0.511530
2013-01-05 -1.909196 -1.047267 -0.264858 -0.839969

In [104]:
df.tail() ##데이터 프레임의 아래 n개항목 표시

                   A         B         C         D
2013-01-02 -0.734789  0.080896 -0.560598  1.824775
2013-01-03  0.214790  1.465058  0.656087 -1.144362
2013-01-04 -0.140319  0.042732  0.442117 -0.511530
2013-01-05 -1.909196 -1.047267 -0.264858 -0.839969
2013-01-06 -0.711966 -1.916296 -3.634960  0.367112

In [105]:
df.index  #DataFrame의 인덱스 표시해줌

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [106]:
df.columns  #column들을 표시해줌

Index(['A', 'B', 'C', 'D'], dtype='object')

In [107]:
#DataFrame.to_numpy()는 하나의 데이터타입으로 배열을 만들어준다.
#다만 인덱스와 컬럼(속성)을 출력해주지 않는다.
df.to_numpy()
#df는 모두 float기때문에 빠르고 한번에 연산된다.

array([[ 0.29380732,  0.98719267, -0.80932639, -0.11113507],
       [-0.73478857,  0.08089575, -0.56059815,  1.82477477],
       [ 0.21479007,  1.46505844,  0.65608654, -1.1443623 ],
       [-0.14031853,  0.04273164,  0.44211736, -0.51153046],
       [-1.90919592, -1.04726689, -0.26485759, -0.83996876],
       [-0.71196642, -1.9162962 , -3.63495959,  0.36711159]])

In [108]:
df2.to_numpy() #df2는 여러타입이 동시에 존재했기 때문에 numpy에서 자동으로 모두를 포함할 수 있는 최상위 클래스인 object로 만들었다.

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [109]:
#describe() 대략적인 통계결과를 보여준다.
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.497945 -0.064614 -0.695256 -0.069185
std    0.819303  1.254849  1.547772  1.070045
min   -1.909196 -1.916296 -3.634960 -1.144362
25%   -0.729083 -0.774767 -0.747144 -0.757859
50%   -0.426142  0.061814 -0.412728 -0.311333
75%    0.126013  0.760618  0.265374  0.247550
max    0.293807  1.465058  0.656087  1.824775

In [110]:
df.T  #행과 열을 바꿔서 보여준다.

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.293807   -0.734789    0.214790   -0.140319   -1.909196   -0.711966
B    0.987193    0.080896    1.465058    0.042732   -1.047267   -1.916296
C   -0.809326   -0.560598    0.656087    0.442117   -0.264858   -3.634960
D   -0.111135    1.824775   -1.144362   -0.511530   -0.839969    0.367112

**여러가지정렬들**

In [111]:
df.sort_index(axis=1, ascending=False)  
#axis : 0=행, 1=컬럼(열)
#ascending : False=오름차순, True=내림차순

                   D         C         B         A
2013-01-01 -0.111135 -0.809326  0.987193  0.293807
2013-01-02  1.824775 -0.560598  0.080896 -0.734789
2013-01-03 -1.144362  0.656087  1.465058  0.214790
2013-01-04 -0.511530  0.442117  0.042732 -0.140319
2013-01-05 -0.839969 -0.264858 -1.047267 -1.909196
2013-01-06  0.367112 -3.634960 -1.916296 -0.711966

In [112]:
df.sort_values(by="B") #값에 의한 정렬은 어느속성의 값인지 정해줘야 한다.

                   A         B         C         D
2013-01-06 -0.711966 -1.916296 -3.634960  0.367112
2013-01-05 -1.909196 -1.047267 -0.264858 -0.839969
2013-01-04 -0.140319  0.042732  0.442117 -0.511530
2013-01-02 -0.734789  0.080896 -0.560598  1.824775
2013-01-01  0.293807  0.987193 -0.809326 -0.111135
2013-01-03  0.214790  1.465058  0.656087 -1.144362

###**Selection**

In [113]:
#한 컬럼을 선택
df["A"]

2013-01-01    0.293807
2013-01-02   -0.734789
2013-01-03    0.214790
2013-01-04   -0.140319
2013-01-05   -1.909196
2013-01-06   -0.711966
Freq: D, Name: A, dtype: float64

In [114]:
#행에서 범위지정해서 선택
df[0:3]

                   A         B         C         D
2013-01-01  0.293807  0.987193 -0.809326 -0.111135
2013-01-02 -0.734789  0.080896 -0.560598  1.824775
2013-01-03  0.214790  1.465058  0.656087 -1.144362

In [115]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02 -0.734789  0.080896 -0.560598  1.824775
2013-01-03  0.214790  1.465058  0.656087 -1.144362
2013-01-04 -0.140319  0.042732  0.442117 -0.511530

**Selection by label**
: df.loc 사용! (location)

In [116]:
#행 읽기
df.loc[dates[0]]

A    0.293807
B    0.987193
C   -0.809326
D   -0.111135
Name: 2013-01-01 00:00:00, dtype: float64

In [117]:
#행을 읽는데 AB속성까지 가져오기
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  0.293807  0.987193
2013-01-02 -0.734789  0.080896
2013-01-03  0.214790  1.465058
2013-01-04 -0.140319  0.042732
2013-01-05 -1.909196 -1.047267
2013-01-06 -0.711966 -1.916296

In [118]:
#행(label)슬라이싱
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02 -0.734789  0.080896
2013-01-03  0.214790  1.465058
2013-01-04 -0.140319  0.042732

In [119]:
#한 행에 AB속성만
df.loc["20130102", ["A", "B"]]

A   -0.734789
B    0.080896
Name: 2013-01-02 00:00:00, dtype: float64

In [120]:
#한 행의 값을 가져올때
df.loc[dates[0], "A"]

0.29380732368386964

In [121]:
#한행의 값을 더 빠르게 가져오고 싶을떄  한행의 스칼라값을 가져올때 빠르게 쓸 수 있다.
df.at[dates[0], "A"]

0.29380732368386964

**Selection by position**

In [122]:
#행의 인덱스로 값 읽어오기. for문을 사용해서 읽어올때도 이걸사용한다.
df.iloc[3]  #index + location = iloc

A   -0.140319
B    0.042732
C    0.442117
D   -0.511530
Name: 2013-01-04 00:00:00, dtype: float64

In [123]:
df.iloc[3:5, 0:4] #iloc[행 3~5-1까지, 열 0~4까지]

                   A         B         C         D
2013-01-04 -0.140319  0.042732  0.442117 -0.511530
2013-01-05 -1.909196 -1.047267 -0.264858 -0.839969

In [124]:
df.iloc[[1, 2, 3], [0, 2]] #[1,2,3행][0, 2열 읽어오기]

                   A         C
2013-01-02 -0.734789 -0.560598
2013-01-03  0.214790  0.656087
2013-01-04 -0.140319  0.442117

In [125]:
df.iloc[:, 1:3]

                   B         C
2013-01-01  0.987193 -0.809326
2013-01-02  0.080896 -0.560598
2013-01-03  1.465058  0.656087
2013-01-04  0.042732  0.442117
2013-01-05 -1.047267 -0.264858
2013-01-06 -1.916296 -3.634960

In [126]:
#값 가져오기
df.iloc[1, 1]

0.08089574645623729

In [127]:
#값에 더 빠르게 가져오기
df.iat[1,1]

0.08089574645623729

**Boolean indexing**

In [128]:
#A열 값이 0보다 큰것만 가져오기
df[df["A"]>0]

                   A         B         C         D
2013-01-01  0.293807  0.987193 -0.809326 -0.111135
2013-01-03  0.214790  1.465058  0.656087 -1.144362

In [129]:
#df가 0이상인 행만 표시
df[df>0]

                   A         B         C         D
2013-01-01  0.293807  0.987193       NaN       NaN
2013-01-02       NaN  0.080896       NaN  1.824775
2013-01-03  0.214790  1.465058  0.656087       NaN
2013-01-04       NaN  0.042732  0.442117       NaN
2013-01-05       NaN       NaN       NaN       NaN
2013-01-06       NaN       NaN       NaN  0.367112

In [130]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]  ##새로운 열 추가
df2

                   A         B         C         D      E
2013-01-01  0.293807  0.987193 -0.809326 -0.111135    one
2013-01-02 -0.734789  0.080896 -0.560598  1.824775    one
2013-01-03  0.214790  1.465058  0.656087 -1.144362    two
2013-01-04 -0.140319  0.042732  0.442117 -0.511530  three
2013-01-05 -1.909196 -1.047267 -0.264858 -0.839969   four
2013-01-06 -0.711966 -1.916296 -3.634960  0.367112  three

In [131]:
df2[df2["E"].isin(["two", "four"])]  # df2에서 df2의 E열에 two 나 four인것만 출력

                   A         B         C         D     E
2013-01-03  0.214790  1.465058  0.656087 -1.144362   two
2013-01-05 -1.909196 -1.047267 -0.264858 -0.839969  four

**Setting**

In [132]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))

In [133]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [134]:
df["F"] = s1

In [135]:
df.at[dates[0], "A"] = 0 #0행에 0열에 값 0

In [136]:
df.iat[0, 1] = 0 #0행에 1열 값 0

In [137]:
df.loc[:, "D"] = np.array([5] * len(df)) # "D"에 [5]를 df의 행 개수많큼 넣겠다

In [138]:
df

                   A         B         C  D    F
2013-01-01  0.000000  0.000000 -0.809326  5  NaN
2013-01-02 -0.734789  0.080896 -0.560598  5  1.0
2013-01-03  0.214790  1.465058  0.656087  5  2.0
2013-01-04 -0.140319  0.042732  0.442117  5  3.0
2013-01-05 -1.909196 -1.047267 -0.264858  5  4.0
2013-01-06 -0.711966 -1.916296 -3.634960  5  5.0

In [139]:
df2 = df.copy()     ## 특정 조건에의한 검색
df2[df2>0] = -df2
df2

                   A         B         C  D    F
2013-01-01  0.000000  0.000000 -0.809326 -5  NaN
2013-01-02 -0.734789 -0.080896 -0.560598 -5 -1.0
2013-01-03 -0.214790 -1.465058 -0.656087 -5 -2.0
2013-01-04 -0.140319 -0.042732 -0.442117 -5 -3.0
2013-01-05 -1.909196 -1.047267 -0.264858 -5 -4.0
2013-01-06 -0.711966 -1.916296 -3.634960 -5 -5.0

### **Missing data**

In [140]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
df1

                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000 -0.809326  5  NaN  1.0
2013-01-02 -0.734789  0.080896 -0.560598  5  1.0  1.0
2013-01-03  0.214790  1.465058  0.656087  5  2.0  NaN
2013-01-04 -0.140319  0.042732  0.442117  5  3.0  NaN

In [141]:
#널값이 있는 행을 드롭
df1.dropna(how="any")

                   A         B         C  D    F    E
2013-01-02 -0.734789  0.080896 -0.560598  5  1.0  1.0

In [142]:
#missing data 채우기 
df1.fillna(value=5)

                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000 -0.809326  5  5.0  1.0
2013-01-02 -0.734789  0.080896 -0.560598  5  1.0  1.0
2013-01-03  0.214790  1.465058  0.656087  5  2.0  5.0
2013-01-04 -0.140319  0.042732  0.442117  5  3.0  5.0

In [143]:
#널값인지 확인하기
pd.isna(df1)

                A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

###**Operations**

**Stats**

In [144]:
df.mean()

A   -0.546913
B   -0.229146
C   -0.695256
D    5.000000
F    3.000000
dtype: float64

In [145]:
#같은 연산을 행 측면으로
df.mean(1)

2013-01-01    1.047668
2013-01-02    0.957102
2013-01-03    1.867187
2013-01-04    1.668906
2013-01-05    1.155736
2013-01-06    0.747356
Freq: D, dtype: float64

In [146]:
#Series생성, 아래로 시프트 2칸(null)로 채워짐
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
print(s)
print(df)

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64
                   A         B         C  D    F
2013-01-01  0.000000  0.000000 -0.809326  5  NaN
2013-01-02 -0.734789  0.080896 -0.560598  5  1.0
2013-01-03  0.214790  1.465058  0.656087  5  2.0
2013-01-04 -0.140319  0.042732  0.442117  5  3.0
2013-01-05 -1.909196 -1.047267 -0.264858  5  4.0
2013-01-06 -0.711966 -1.916296 -3.634960  5  5.0

In [147]:
#df에서 s를 뺌, Nan과 연산된것은 NaN이됨
df.sub(s, axis="index")

                   A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -0.785210  0.465058 -0.343913  4.0  1.0
2013-01-04 -3.140319 -2.957268 -2.557883  2.0  0.0
2013-01-05 -6.909196 -6.047267 -5.264858  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

In [148]:
df.sub(s, axis=0)

                   A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -0.785210  0.465058 -0.343913  4.0  1.0
2013-01-04 -3.140319 -2.957268 -2.557883  2.0  0.0
2013-01-05 -6.909196 -6.047267 -5.264858  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

Apply

In [149]:
df.apply(np.cumsum)

                   A         B         C   D     F
2013-01-01  0.000000  0.000000 -0.809326   5   NaN
2013-01-02 -0.734789  0.080896 -1.369925  10   1.0
2013-01-03 -0.519999  1.545954 -0.713838  15   3.0
2013-01-04 -0.660317  1.588686 -0.271721  20   6.0
2013-01-05 -2.569513  0.541419 -0.536578  25  10.0
2013-01-06 -3.281479 -1.374877 -4.171538  30  15.0

In [150]:
df.describe()

              A         B         C    D         F
count  6.000000  6.000000  6.000000  6.0  5.000000
mean  -0.546913 -0.229146 -0.695256  5.0  3.000000
std    0.769802  1.149668  1.547772  0.0  1.581139
min   -1.909196 -1.916296 -3.634960  5.0  1.000000
25%   -0.729083 -0.785450 -0.747144  5.0  2.000000
50%   -0.426142  0.021366 -0.412728  5.0  3.000000
75%   -0.035080  0.071355  0.265374  5.0  4.000000
max    0.214790  1.465058  0.656087  5.0  5.000000

In [151]:
df.apply(lambda x: x.max() - x.min())

A    2.123986
B    3.381355
C    4.291046
D    0.000000
F    4.000000
dtype: float64

 Histogramming

In [152]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    1
1    2
2    3
3    3
4    3
5    3
6    4
7    3
8    1
9    6
dtype: int64

In [153]:
s.value_counts()

3    5
1    2
6    1
4    1
2    1
dtype: int64

**String Methods**

In [154]:
s = pd.Series(["A", "B", "C", "AaBa", "Baca", np.nan, "CABA", "dog", "cat"])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [155]:
s.str.upper()

0       A
1       B
2       C
3    AABA
4    BACA
5     NaN
6    CABA
7     DOG
8     CAT
dtype: object

###**Merge**

**Concat**
DataFrame에서 열 추가는 매우 빠르지만
행 추가는 느릴수가 있다.
따라서 미리 만들어진 DataFrame에 넣는것이 효율적일 수 있다.

In [156]:
df = pd.DataFrame(np.random.randn(10,4)) # 10행 4열 랜덤값으로 채워놓음
df

          0         1         2         3
0 -0.934709 -1.006755 -0.763551 -0.011665
1  0.974262  0.444291  0.943812  0.177870
2 -0.779588  1.052130 -1.653886  0.528191
3  0.698655 -0.729490  2.514822  1.832916
4 -1.664620  0.985387 -0.668103 -0.867657
5 -0.738001 -1.580447  1.048142  0.419117
6 -1.002164 -0.479507 -1.231416  1.211391
7 -0.179943 -0.431046  0.144342  0.852541
8 -1.990235  1.349989  0.242133 -0.638619
9 -2.455704  0.743950 -0.897920 -0.264479

In [157]:
#pieces로 나눠버림
pieces = [df[:3], df[3:7], df[7:]]
pieces

[          0         1         2         3
 0 -0.934709 -1.006755 -0.763551 -0.011665
 1  0.974262  0.444291  0.943812  0.177870
 2 -0.779588  1.052130 -1.653886  0.528191,
           0         1         2         3
 3  0.698655 -0.729490  2.514822  1.832916
 4 -1.664620  0.985387 -0.668103 -0.867657
 5 -0.738001 -1.580447  1.048142  0.419117
 6 -1.002164 -0.479507 -1.231416  1.211391,
           0         1         2         3
 7 -0.179943 -0.431046  0.144342  0.852541
 8 -1.990235  1.349989  0.242133 -0.638619
 9 -2.455704  0.743950 -0.897920 -0.264479]

In [158]:
pd.concat(pieces)

          0         1         2         3
0 -0.934709 -1.006755 -0.763551 -0.011665
1  0.974262  0.444291  0.943812  0.177870
2 -0.779588  1.052130 -1.653886  0.528191
3  0.698655 -0.729490  2.514822  1.832916
4 -1.664620  0.985387 -0.668103 -0.867657
5 -0.738001 -1.580447  1.048142  0.419117
6 -1.002164 -0.479507 -1.231416  1.211391
7 -0.179943 -0.431046  0.144342  0.852541
8 -1.990235  1.349989  0.242133 -0.638619
9 -2.455704  0.743950 -0.897920 -0.264479

**Join**

In [159]:
left = pd.DataFrame({"key" : ["foo", "foo"], "lval" : [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo"], "rval" : [4, 5]})
left

   key  lval
0  foo     1
1  foo     2

In [160]:
right

   key  rval
0  foo     4
1  foo     5

In [161]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [162]:
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "bar"], "lval": [4, 5]})
left

   key  lval
0  foo     1
1  bar     2

In [163]:
right

   key  lval
0  foo     4
1  bar     5

In [164]:
pd.merge(left, right, on="key")

   key  lval_x  lval_y
0  foo       1       4
1  bar       2       5

###**Grouping**

group by는 아래 단계를 밟는다.
-. Splitting  데이터를 나눌  기준
-. Applying 각 데이터에 독립적으로 적용할 함수
-. Combining 데이터구조 결과

In [165]:
df = pd.DataFrame({
    "A" : ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
    "B" : ["one", "one", "two", "three", "two", "two", "one", "three"],
    "C": np.random.randn(8),
    "D": np.random.randn(8)                                     
})

df

     A      B         C         D
0  foo    one -1.341183  1.841194
1  bar    one  0.600780 -0.250414
2  foo    two -0.604663  1.192498
3  bar  three -1.236316  0.509730
4  foo    two  0.587282  0.014840
5  bar    two -0.576917  0.702592
6  foo    one  0.735456  0.336116
7  foo  three  0.809991  0.075477

In [166]:
#그룹핑과 apply로 sum()하기, B는 더할수 없는 문자열이기때문에 빠진듯 하다.
df.groupby("A").sum()

            C         D
A
bar -1.212454  0.961909
foo  0.186884  3.460124

###**Reshaping**
**Stack**  열의 정보를 행의 정보로 만들어줌

In [167]:
tuples = list(
    zip(
        *[
          ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
          ["one", "two", "one", "two", "one", "two", "one", "two"],
        ]
    )
)

index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index = index, columns=["A", "B"])
df2 = df[:]
df2

                     A         B
first second
bar   one    -0.677418  2.625702
      two    -0.596267 -3.796475
baz   one    -0.719533 -0.174554
      two     2.107043 -0.387970
foo   one     1.105191 -0.579635
      two     0.483344  1.384723
qux   one     0.898947 -0.601221
      two    -0.819400 -0.674476

In [168]:
stacked = df2.stack()
stacked

first  second
bar    one     A   -0.677418
               B    2.625702
       two     A   -0.596267
               B   -3.796475
baz    one     A   -0.719533
               B   -0.174554
       two     A    2.107043
               B   -0.387970
foo    one     A    1.105191
               B   -0.579635
       two     A    0.483344
               B    1.384723
qux    one     A    0.898947
               B   -0.601221
       two     A   -0.819400
               B   -0.674476
dtype: float64

In [169]:
stacked.unstack()   #반대로 행을 열로 만들어준다

                     A         B
first second
bar   one    -0.677418  2.625702
      two    -0.596267 -3.796475
baz   one    -0.719533 -0.174554
      two     2.107043 -0.387970
foo   one     1.105191 -0.579635
      two     0.483344  1.384723
qux   one     0.898947 -0.601221
      two    -0.819400 -0.674476

In [170]:
stacked.unstack(1)

second        one       two
first
bar   A -0.677418 -0.596267
      B  2.625702 -3.796475
baz   A -0.719533  2.107043
      B -0.174554 -0.387970
foo   A  1.105191  0.483344
      B -0.579635  1.384723
qux   A  0.898947 -0.819400
      B -0.601221 -0.674476

In [171]:
stacked.unstack(0)

first          bar       baz       foo       qux
second
one    A -0.677418 -0.719533  1.105191  0.898947
       B  2.625702 -0.174554 -0.579635 -0.601221
two    A -0.596267  2.107043  0.483344 -0.819400
       B -3.796475 -0.387970  1.384723 -0.674476

**Pivot tables**

In [172]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
            "B": ["A", "B", "C"] * 4,
            "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
            "D": np.random.randn(12),
            "E": np.random.randn(12),
    }
)

df

        A  B    C         D         E
0     one  A  foo  1.833655  0.257735
1     one  B  foo -1.118237 -0.777939
2     two  C  foo -1.055332  0.298864
3   three  A  bar  0.072638  1.060607
4     one  B  bar -0.420884 -3.108512
5     one  C  bar -1.775147 -0.395223
6     two  A  foo  0.394632 -0.205821
7   three  B  foo -0.376356 -1.250908
8     one  C  foo  0.071801 -0.615723
9     one  A  bar  0.418645 -0.156803
10    two  B  bar  0.397948 -0.470544
11  three  C  bar -0.863469  1.134786

In [173]:
pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"])

C             bar       foo
A     B
one   A  0.418645  1.833655
      B -0.420884 -1.118237
      C -1.775147  0.071801
three A  0.072638       NaN
      B       NaN -0.376356
      C -0.863469       NaN
two   A       NaN  0.394632
      B  0.397948       NaN
      C       NaN -1.055332

###**Time series**

In [180]:
rng =pd.date_range("1/1/2012", periods=100, freq="S")
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts.resample("5Min").sum()

2012-01-01    25653
Freq: 5T, dtype: int64

In [182]:
rng = pd.date_range("3/6/2012 00:00", periods=5, freq="D")
ts = pd.Series(np.random.randn(len(rng)), rng)
ts

2012-03-06    1.450102
2012-03-07    0.402236
2012-03-08    1.468203
2012-03-09   -1.528185
2012-03-10   -1.420881
Freq: D, dtype: float64

In [185]:
ts_utc = ts.tz_localize("UTC")
ts_utc

2012-03-06 00:00:00+00:00    1.450102
2012-03-07 00:00:00+00:00    0.402236
2012-03-08 00:00:00+00:00    1.468203
2012-03-09 00:00:00+00:00   -1.528185
2012-03-10 00:00:00+00:00   -1.420881
Freq: D, dtype: float64

In [186]:
ts_utc.tz_convert("US/Eastern")

2012-03-05 19:00:00-05:00    1.450102
2012-03-06 19:00:00-05:00    0.402236
2012-03-07 19:00:00-05:00    1.468203
2012-03-08 19:00:00-05:00   -1.528185
2012-03-09 19:00:00-05:00   -1.420881
Freq: D, dtype: float64

In [190]:
rng = pd.date_range("1/1/2012", periods=5, freq="M")
ts = pd.Series(np.random.randn(len(rng)), index=rng)
ts

2012-01-31    0.435631
2012-02-29   -0.972131
2012-03-31   -0.055670
2012-04-30   -0.862989
2012-05-31   -0.810350
Freq: M, dtype: float64

In [191]:
ps = ts.to_period()
ps

2012-01    0.435631
2012-02   -0.972131
2012-03   -0.055670
2012-04   -0.862989
2012-05   -0.810350
Freq: M, dtype: float64

In [192]:
ps.to_timestamp()

2012-01-01    0.435631
2012-02-01   -0.972131
2012-03-01   -0.055670
2012-04-01   -0.862989
2012-05-01   -0.810350
Freq: MS, dtype: float64