###**(실습. 년도를 입력받아 윤년인지 아닌지 판별하는 함수(leap_year)를 작성**
1.화면에서 연도를 입력
2. 윤년이면 "윤년" 아니면 "평년"을 출력
3. 윤년은 (2월이 29일까지)
  - 4로 나눠서 떨어지면 윤년
  - 4, 100으로 나눠서 떨어지면 평년
  - 4, 100, 400으로 나눠서 떨어지면 윤년

In [9]:
def leap_year(year):
  ch = "평"
  if year % 4 == 0:
    ch = "윤"
    if year % 100 == 0:
      ch = "평"
      if year % 400 == 0:
        ch = "윤"
  return ch

def leap_year2(year):
  ch = False
  if year % 4 == 0:
    ch = True
    if year % 100 == 0:
      ch = False
      if year % 400 == 0:
        ch = True
  return ch

In [15]:
years = [1900, 1988, 2000, 2008, 2020, 2100, 2400]
for i in years:
  print(i, "년은 ", leap_year(i), "년 입니다.", sep="")

print(list(map(leap_year, years)))

print(years,"중에서 윤년은", list(filter(leap_year2, years)), "입니다.")

1900년은 평년 입니다.
1988년은 윤년 입니다.
2000년은 윤년 입니다.
2008년은 윤년 입니다.
2020년은 윤년 입니다.
2100년은 평년 입니다.
2400년은 윤년 입니다.
['평', '윤', '윤', '윤', '윤', '평', '윤']
[1900, 1988, 2000, 2008, 2020, 2100, 2400] 중에서 윤년은 [1988, 2000, 2008, 2020, 2400] 입니다.

In [17]:
list(map((lambda year : "윤년" if ((year%4==0) and (year%100 != 0) or (year%400 == 0)) else "평년"), years))

['평년', '윤년', '윤년', '윤년', '윤년', '평년', '윤년']

###**(반복처리)**
1. for()함수 leap_year() 사용해서
2. aa의 결과값을 y로 만들기

In [21]:
aa = [1980, 2019, 2020]

for year in aa:
  print("year = ", leap_year(year), "년", sep="")

year = 윤년
year = 평년
year = 윤년

###**(while)**
1. 화면에서 연도를 입력받아 윤년, 평년 판별
2. 화면에서 0이면 while문 종려료

In [24]:
y = []
while True:
  year = int(input("연도를 입력하세요"))
  if year == 0:
    break;
  result = leap_year(year)
  y.append([year, result])
  print(year,"년도는 ", result, "년 입니다.\n", sep="")

print(y)

연도를 입력하세요1990
1990년도는 평년 입니다.

연도를 입력하세요1987
1987년도는 평년 입니다.

연도를 입력하세요1234
1234년도는 평년 입니다.

연도를 입력하세요2020
2020년도는 윤년 입니다.

연도를 입력하세요0
[[1990, '평'], [1987, '평'], [1234, '평'], [2020, '윤']]

In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.DataFrame(data=y, columns=["years", "leap_year"])

In [27]:
df

   years leap_year
0   1990         평
1   1987         평
2   1234         평
3   2020         윤

In [28]:
y = {}
while True:
  year = int(input("연도를 입력하세요"))
  if year == 0:
    break;
  result = leap_year(year)
  y[year] = result
  print(year,"년도는 ", result, "년 입니다.\n", sep="")

print(y)

연도를 입력하세요1980
1980년도는 윤년 입니다.

연도를 입력하세요195
195년도는 평년 입니다.

연도를 입력하세요1995
1995년도는 평년 입니다.

연도를 입력하세요1987
1987년도는 평년 입니다.

연도를 입력하세요2030
2030년도는 평년 입니다.

연도를 입력하세요2020
2020년도는 윤년 입니다.

연도를 입력하세요2010
2010년도는 평년 입니다.

연도를 입력하세요0
{1980: '윤', 195: '평', 1995: '평', 1987: '평', 2030: '평', 2020: '윤', 2010: '평'}

In [33]:
y[1980]

'윤'

In [37]:
y

{195: '평', 1980: '윤', 1987: '평', 1995: '평', 2010: '평', 2020: '윤', 2030: '평'}

In [90]:
df = pd.DataFrame(data=y, index=[""])

In [91]:
df

 1980 195  1995 1987 2030 2020 2010
    윤    평    평    평    평    윤    평

###**(함수 실습, 입력자료에서 홀수, 짝수, 문자열 숫자세는 함수 만들기)**
1. 1, 2, 3, "ab", 6, 7 -> 홀수 3, 짝수 2, 문자 1
2. 입력자료는 몇개가 들어올지 모른다.

In [64]:
def filter_func(item):
  if type(item) == str:
    return "문자"
  elif item%2 == 0:
    return "짝수"
  else:
    return "홀수"

In [65]:
items = [1, 2, 3, "ab", 6, 7]
list(map(filter_func, items))

['홀수', '짝수', '홀수', '문자', '짝수', '홀수']

In [81]:
def count_input(*args):
  y = {
      "문자" : 0,
      "짝수" : 0,
      "홀수" : 0
  }
  ch =""
  for item in args:
    if type(item) == str:
      ch  = "문자"
    elif item%2 == 0:
      ch = "짝수"
    else:
      ch = "홀수"
    y[ch] += 1
    print(ch)
  return y

In [82]:
print(count_input(1, 2, "a"))

홀수
짝수
문자
{'문자': 1, '짝수': 1, '홀수': 1}

In [88]:
df = pd.DataFrame(data=count_input(1, 2, "a"), index=["item"])

홀수
짝수
문자

In [89]:
df

      문자  짝수  홀수
item   1   1   1